### ISSUE TITLE
Issue when creating first app using ionic2

### ISSUE THREAD

**Issue by abhishekbhutra** [driftyco/ionic-cli#1056]
Getting this error 

```
$ ionic start cutePuppyPics --v2
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please update your Node runtime to version  >=0.12.x
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
Creating Ionic app in folder /Users/abhishekbhutra/projects/playground/ionic2/cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by cnrblm** [comment]
+1

**Comment by tejit2004** [comment]
Same Error. any solution?

**Comment by Siltor94** [comment]
+1

**Comment by gaoqi8985** [comment]
I have the same problem!!!  
"There was an error with the spawned command: npminstall"

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by khertan** [comment]
Same error here :
khertan@x200:~/Projects/MyIonic2Project$ ionic info

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.5 (jessie) 
Node Version: v4.4.3

**Comment by blackburnian** [comment]
Same error for me

ionic info

Your system information:

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jthoms1** [comment]
Could you try running the command with the verbose flag?  I have a feeling that everyone is receiving this same issue due to node-sass.

`ionic start cutePuppyPics --v2 --verbose`

**Comment by msatyan** [comment]
Same error on Windows 10; please see the attachment output for 
 ionic start cutePuppyPics --v2 --verbose 

C:\>ionic info
Your system information:
Cordova CLI: 6.2.0
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v4.2.3

[start.out.txt](https://github.com/driftyco/ionic-cli/files/315230/start.out.txt)

**Comment by blackburnian** [comment]
My output from ```ionic start cutePuppyPics --v2 --verbose``` attached as well
[output.txt](https://github.com/driftyco/ionic-cli/files/315403/output.txt)

**Comment by jthoms1** [comment]
@blackburnian Could you try that again? The error about angular not appearing in NPM is unexpected and could be a problem that was intermittent with NPM.

@msatyan The issue you are experiencing is due to the fact that your NPM install was done as administrator and the current command prompt you have open is not.  Try opening a new prompt as an admin. This should resolve the issue for you.

**Comment by blackburnian** [comment]
@jthoms1 I tried it again.  Still getting an angular error.

[output2.txt](https://github.com/driftyco/ionic-cli/files/316449/output2.txt)

**Comment by msatyan** [comment]
Thanks jthoms1, Yes, the install problem got solved.
Have a nice day.

**Comment by abhishekbhutra** [comment]
So I have tried a couple of things updating, ionic-cli and npm. I am not sure what solved my problem, but it is working now.

My system info now is 


**

```
Your system information:

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 2.0.1 
OS: Mac OS X El Capitan
Node Version: v6.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014 


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
```

**

**Comment by abhishekbhutra** [comment]
But there is another issue, I am running into. When I run any ionic command, ionic build ios/android the output is some unreadable bytes. Something like this, if anyone can help me with this.

`0=99, 1=112, 2=58, 3=32, 4=110, 5=111, 6=32, 7=115, 8=117, 9=99, 10=104, 11=32, 12=102, 13=105, 14=108, 15=101, 16=32, 17=111, 18=114, 19=32, 20=100, 21=105, 22=114, 23=101, 24=99, 25=116, 26=111, 27=114, 28=121, 29=58, 30=32, 31=47, 32=85, 33=115, 34=101, 35=114, 36=115, 37=47, 38=97, 39=98, 40=104, 41=105, 42=115, 43=104, 44=101, 45=107, 46=98, 47=104, 48=117, 49=116, 50=114, 51=97, 52=47, 53=112, 54=114, 55=111, 56=106, 57=101, 58=99, 59=116, 60=115, 61=47, 62=112, 63=108, 64=97, 65=121, 66=103, 67=114, 68=111, 69=117, 70=110, 71=100, 72=47, 73=105, 74=111, 75=110, 76=105, 77=99, 78=50, 79=47, 80=84, 81=101, 82=120, 83=116, 84=45, 85=105, 86=110, 87=45, 88=97, 89=112, 90=112, 91=32, 92=99, 93=105, 94=101, 95=47, 96=114, 97=101, 98=115, 99=111, 100=117, 101=114, 102=99, 103=101, 104=115, 105=47, 106=105, 107=111, 108=115, 109=47, 110=105, 111=99, 112=111, 113=110, 114=47, 115=105, 116=99, 117=111, 118=110, 119=45, 120=54, 121=48, 122=46, 123=112, 124=110, 125=103, 126=10, 127=10`

**Comment by khertan** [comment]
For me the problem on debian was two different version of node mixed together. 0.10 and 4.x

Problem solved for me after clean node reinstall.
Regards

**Comment by blackburnian** [comment]
I tried updating node and npm with no success.  Finally, I uninstalled node, npm, nvm, ionic, and cordova.  Reinstalled nvm, and used that to reinstall node/npm, then reinstalled the others.  This fixed the issue for me.

**Comment by jthoms1** [comment]
Closing this as a duplicate of #1013.

**Comment by swathir** [comment]
Try running it with sudo.

**Comment by AbinayaVenkat** [comment]
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 7 SP1
Node Version: v6.9.1
npm ERR! node-sass@3.10.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.10.1 postinstall script 'node scripts/build.j
s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shanma1\Project\npm-debug.log
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by AbinayaVenkat** [comment]
got the issue resolved with "npm config set https_proxy http://proxy.cat.com:8080"
