### ISSUE TITLE
Ionic Error: Platform ios already added. but when running resources, says no platform added

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1068]
_From @LydiaMontagnese on June 11, 2016 22:39_

#### Short description of the problem:

When I run 'ionic platform add ios', I am getting this error: 
Error: Platform ios already added. 

But when running 'ionic resources', it says no platform added.

Here's the output:

Lydias-MBP:ionic-basic lydia$ ionic resources
No platforms have been added.
Please add a platform, for example: ionic platform add ios
Or provide a platform name, for example: ionic resources android

Lydias-MBP:ionic-basic lydia$ ionic platform add ios
 ✗ (node:51934) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Updated the hooks directory to have execute permissions
Error: Platform ios already added.

Lydias-MBP:ionic-basic lydia$ 

_Copied from original issue: driftyco/ionic#6868_

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue is an issue with the Ionic CLI and not the framework I will be moving this issue to the correct repo. Thanks for using Ionic!

**Comment by irthos** [comment]
+1 having the same issue

**Comment by LydiaMontagnese** [comment]
@irthos I think I fixed my issue by deleting any node-modules or ionic-related files I had in my home (your username) directory. It appears my app thought I already had the platform added because it was added in a project in that directory.

**Comment by tuongaz** [comment]
There may be a 'platform' folder above your current directory,

**Comment by cyrinearbi** [comment]
Hi,I have the same problem !!!  
$ sudo cordova platform add ios --save
Using cordova-fetch for cordova-ios@^4.4.0
Error: Platform ios already added.

**Comment by SanjayYadav90** [comment]
There was same issue with me, this caused because I changed app name in config file.
I used these commands-
```
	cordova plugin save
	cordova platform rm ios
	cordova platform add ios
```
but error remain same.
I open app/platform/, and saw there was ios file then here is what I did-

1. Removed ios file (Manually).  
2. Run sudo cordova platform add ios --save
3. ios platform added for me.

**Comment by luisabarca** [comment]
This worked for me.
`
# Go to your app folder
cd yourapp

# Create the platforms folder
mkdir platforms

# Run the command again
ionic cordova platform add ios
`
