### ISSUE TITLE
Ionic serve --l not working

### ISSUE THREAD

**Issue by MELAS007** [driftyco/ionic-cli#1654]
i didn't have this problem before just today, when i run ionic serve --l it appears this issue: 

$ ionic serve --l

> ionic-hello-world@ ionic:serve D:\Mobile apps\test\StorageDataAPP
> ionic-app-scripts serve "[object Object]"

D:\Mobile apps\test\StorageDataAPP\node_modules\node-sass\lib\index.js:15
    throw new Error(errors.missingBinary());
    ^

Error: Missing binding D:\Mobile apps\test\StorageDataAPP\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (D:\Mobile apps\test\StorageDataAPP\node_modules\node-sass\lib\index.js:15:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile apps\test\StorageDataAPP\node_modules\@ionic\app-scripts\dist\sass.js:10:19)
    at Module._compile (module.js:570:32)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\MELAS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "[object Object]"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "[object Object]"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "[object Object]"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "[object Object]"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Mobile apps\test\StorageDataAPP\npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

what is it?

any one can help to solve this?

**Comment by anashmamouch** [comment]
Hi, i'm having the same issue but with another package "node-sass" 
npm rebuild node-sass worked for me, i think according to your log you should run `npm rebuild npm-cli`. 

This is happening since the last upgrade i hope we get a quick fix from the ionic team.

**Comment by MELAS007** [comment]
@anashmamouch - it is not working for me!

**Comment by MELAS007** [comment]
any news?  I / we can't work!!!!

**Comment by PEZO19** [comment]
ionic serve WORKED IN ONE SECOND, THEN IT STOPPED! What is happening?!?!

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pezo/GoogleDrive/_PEZO/Projektek/IONIC/myAwesomeApp/npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

**Comment by MELAS007** [comment]
I re-install ionic and tried it - ionic serve -l, it opens with this "Cannot GET //__ion-dev-server/ionic_lab.html".

so?

**Comment by jthoms1** [comment]
Please update your CLI and app-scripts.  We had a regression end of last week, but this should all be fixed now.

Please install ionic@2.1.8 and @ionic/app-scripts@0.0.44

**Comment by MELAS007** [comment]
@jthoms1 - Could you tell me how to install @ionic/app-scripts@0.0.44????

**Comment by adirzoari** [comment]
@jthoms1 @MELAS007    i have the same issue i get these error
`> ionic-app-scripts serve

[02:12:07]  ionic-app-scripts 0.0.45
[02:12:07]  watch started ...
[02:12:07]  build dev started ...
[02:12:07]  clean started ...
[02:12:07]  clean finished in less than 1 ms
[02:12:07]  copy started ...
[02:12:07]  transpile started ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8100
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\adirz\myapps\pelephoneYossi\npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve`

**Comment by lingyilun** [comment]
@MELAS007    npm install @ionic/app-scripts@latest --save-dev  
But the problem persists

**Comment by theunreal** [comment]
Same error here, just tried to start with Ionic and followed the docs (http://ionicframework.com/docs/v2/getting-started/installation/)

**Comment by pranay222** [comment]
I was having the issue. Now it's resolved, here's the secret:

While starting the app:
use '--v2'
`ionic start myApp blank --v2`

Then when you run `ionic serve` all should run fine!

**Comment by burhangul** [comment]
You must upgrade your `node version`. if that is not working:
"scripts": {
   "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  }, 
add these codes to your package.json

**Comment by MELAS007** [comment]
@burhangul  - i use node v.6.9.1 is it ok?

**Comment by burhangul** [comment]
Me to used node v.6.9.1 but its not worked. I upgraded node to latest version and its working now. My node version 7.2.1 at now

**Comment by Marcusjmb** [comment]
Try to kill the ionic service and run it again. It works for me with 99% of the time.
kill -9 <PID>

**Comment by foaudkajj** [comment]
I got a similar problem and I solved it by just adjusting one wrong path of a component in the main component ( **app.component.ts** )
