### ISSUE TITLE
Ionic Upload Fails.

### ISSUE THREAD

**Issue by nobesio** [driftyco/ionic-cli#177]
Hey, I have been recently trying to use ionic's upload command in order to test my app from Ionic View but when I run the command it concludes really fast without saying the upload was successful or the upload identifier. Before doing this I update Ionic's version to 1.3.1. Here are some screenshots.

![screen shot 2015-01-13 at 10 57 05 am](https://cloud.githubusercontent.com/assets/9274069/5721661/f4f27672-9b12-11e4-81ca-6a866695836f.png)

Thanks you very much.

**Comment by jbavari** [comment]
Thanks for reporting. We just came about this. I'm working on it right now.

**Comment by jbavari** [comment]
This should be fixed in the latest in master. I'll be pushing to 1.3.2 soon.

**Comment by nobesio** [comment]
Thanks you very much!

**Comment by cfjedimaster** [comment]
Heh nice I was just about to log this.

**Comment by jasoncartermartin** [comment]
I'm having the exact same problem...it says it's uploading, but returns really fast as if it were successful, but I doubt it is doing anything.

Still can't access my app in the ionic view iOS app.

**Comment by cfjedimaster** [comment]
Doing ionic upload a second time fixed it for me.

**Comment by tlaverdure** [comment]
I was having an issue with uploading one of my apps and noticed a difference with my ionic.project file from another project that was uploading successfully. The name of my app in ionic.project read "true". I updated that to the actual name of the app and afterwards the app uploaded successfully. Hope this helps.

**Comment by jbavari** [comment]
@tlaverdure - we've noticed a few of circumstances for that. Also, some users go and add their own appId in the ionic.project file as well.

Thanks for the heads up. Closing for now.
