### ISSUE TITLE
ionic.project not passing in correctly to ionic serve

### ISSUE THREAD

**Issue by mattchue** [driftyco/ionic-cli#453]
Just updated to the latest version of the CLI and now I am receiving this error. I have been able to serve this project before without any issue. Reverting to CLI 1.4.5 fixes this problem.

````
Serve.loadSettings - You must pass a project object to pull out project specific settings from

Error: Serve.loadSettings - You must pass a project object to pull out project specific settings from
    at Object.loadSettings (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:153:11)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/serve.js:30:23)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:71:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

Serve.loadSettings - You must pass a project object to pull out project specific settings from (CLI v1.4.8)

Your system information:

Cordova CLI: 4.3.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: 1.4.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.36
Xcode version: Xcode 6.3.1 Build version 6D1002
````

**Comment by alexkavon** [comment]
Can confirm this is happening on OS X and Windows.

**Comment by MattBrodrecht** [comment]
Same error here

**Comment by jbavari** [comment]
I messed up - didnt merge my changes back to master when Max did a release. I'll patch now and fix.

In the meantime, can you stick with 1.4.5? `npm install -g ionic@1.4.5`

**Comment by johnking** [comment]
Had the same issue here with Windows 7.

**Comment by saniyusuf** [comment]
Thank God I aint the only one

**Comment by naokichau** [comment]
How can i revert to older cli ver?

**Comment by umeshiyer** [comment]
Had the same problem on OS X. jbavari's suggestion worked. Waiting for the upgrade. Thanks

**Comment by drmaq** [comment]
The patch worked.

**Comment by ev-tt** [comment]
How to apply this patch?

**Comment by jbavari** [comment]
This should be fixed in 1.5.0.

Install with `npm install -g ionic`

**Comment by diego-oliveira** [comment]
Having the same issue here, upgrading to version 1.5.0 solved the issue

**Comment by mattchue** [comment]
@jbavari This is fixed for me with 1.5.0. Thanks for the swift response!

**Comment by ducnguyenhuy** [comment]
I have update ionic version 1.6.1 but this issue still happens:

The below is ionic info on my machine.
Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b 

Do you have any idea to fix this? Thanks a lot.

**Comment by chandanch** [comment]
I also have the same issue here:

https://github.com/driftyco/ionic-cli/issues/981
