### ISSUE TITLE
feat: Make Crosswalk default browser for Android

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#546]
_From @csvan on August 1, 2015 20:53_

**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Apart from the app size inflation (15-20MB as of current), are there any good reasons for not making Crosswalk the default runtime for Android deployments?

Apart from the obvious boosts to overall performance and rendering, this would make overall development of the core platform easier by eliminating Webview issues specific to different Android versions. It would also make things easier for developers, since potential issues and questions can be discussed w.r.t. only a single browser. </span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4176_

**Comment by trazek** [comment]
It seems CrossWalk has a bug with Android 5 

https://crosswalk-project.org/jira/browse/XWALK-2958

**Comment by spyjo** [comment]
What about RAM usage (and CPU) ? Compatibility of 100% of plugins and native functionality ?

**Comment by baleboy** [comment]
@trazek for the records, the actual active bug for that issue is https://crosswalk-project.org/jira/browse/XWALK-4738

Let us know (here or in our Jira) of any other bugs preventing Crosswalk from becoming the default, we'll try to prioritize.

The Crosswalk Team

**Comment by csvan** [comment]
@spyjo - I may be off, but Crosswalk **should** outperform the native WV in terms of both, regardless if you run Android 4 or 5.

**Comment by spyjo** [comment]
Then, I suppose these 2 lists should be checked, to fix what needs to be fixed:
https://github.com/driftyco/ionic-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+crosswalk
https://github.com/driftyco/ionic/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+crosswalk

**Comment by csvan** [comment]
As far as compatibility goes, the only problematic plugin I know is localNotification. However, it seems to be going deeper than just Crosswalk (and the workaround is simple, anyway):

https://github.com/katzer/cordova-plugin-local-notifications/issues/426#issuecomment-129403161

**Comment by ObjectiveTruth** [comment]
@csvan, that issue was just recently fixed via this PR :+1:

https://github.com/davidpiegza/cordova-plugin-local-notifications/pull/2

**Comment by baleboy** [comment]
After looking through the issues here and elsewhere, there seem to be two main problems that people have experienced which would prevent Crosswalk from being enabled by default:

* flickering/resizing/flashing screen when opening and closing virtual keyboard. For some people this is fixed by setting ANIMATABLE_XWALK_VIEW to true, but for some the only solution is to upgrade to Crosswalk 15
* not migrating local storage data when upgrading an existing app from platform webview to Crosswalk. This is also fixed in Crosswalk 15

The tricky thing is that the current release of cordova-plugin-crosswalk-webview in NPM (1.2.0) doesn't work with Crosswalk 15 because of some API changes. We are going to release an update next week, but meanwhile anybody who wants to try Crosswalk 15 in their current app needs to install the plugin from GitHub and configure the Crosswalk version (the plugin selects Crosswalk 14 by default):
´´´
cordova plugin add https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview.git#master 
´´´
In config.xml:
´´´
<preference name="xwalkVersion" value="xwalk_core_library_beta:15+" />
´´´
It would be great if someone could test this combination and give us feedback. As far as I can tell, with these versions Crosswalk could be the default webview for Ionic on Android.

**Comment by baleboy** [comment]
A new version of the plugin that supports Crosswalk 15 is on NPM: https://www.npmjs.com/package/cordova-plugin-crosswalk-webview

**Comment by adamdbradley** [comment]
Let's go ahead a make crosswalk the default, and require an additional flag if it should not be used.

:shipit:

**Comment by wangyuzju** [comment]
@baleboy 
I'm still get the version 14 of crosswalk installed follow your method:

```
embedded
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
org.xwalk:xwalk_core_library:14+
```

It seems that cordova has cached the crosswalk 14, do you know how to install crosswalk 15?

**Comment by tsurrel** [comment]
@wangyuzju 
You can do like this to specify a version:
ionic browser add crosswalk@15.44.384.9

**Comment by wangyuzju** [comment]
@tsurrel  yes, I have installed crosswalk 15, but it seems that the cookies still can't be shared between crosswalk and native android webview.
