### ISSUE TITLE
Ionic installation fails on node 4.0

### ISSUE THREAD

**Issue by udnisap** [driftyco/ionic-cli#583]
I ran `npm install -g ionic` on node 4.0 and it fails when I switch back to node 0.10.40 it works fine. 

``` 
npm ERR! tar.unpack untar error /tmp/npm-20692-1c1094e5/registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.9.0.tgz
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.0.0
npm ERR! npm  v2.11.3
```

**Comment by jbavari** [comment]
@rumal Would you try running that again? It looks like an issue with one of your packages getting uncompressed.

I was able to install Ionic CLI on Node 4.0 on both Windows and Mac.

**Comment by bineeshmvarghese** [comment]
Solution

Follow the steps
1. Install all necessary dependencies.
http://ionicframework.com/docs/guide/installation.html
2. Uninstall node.js from PC if already installed
3. Restart PC
4. Download and Install node.js (MSI Installer) from http://nodejs.org/dist/v0.10.38/ for x86 or http://nodejs.org/dist/v0.10.38/x64/ for x64
5. Right-click Command prompt, and then click Run as administrator.
6. Install Cordova using the command: npm install -g cordova
7. Finally install Ionic Framework using the command: npm install -g ionic
8. Reinstall nod.js http://nodejs.org/dist/v0.12.7/ for x86 or http://nodejs.org/dist/v0.12.7/x64/ for x64

Done!

**Comment by bankim** [comment]
I am having a problem installing ionic.

Cordova was installed, but I am still getting the below error.

Bankims-MacBook-Pro:Documents bankimdebnath$ sudo npm install -g cordova ionic

tar.unpack untar error /tmp/npm-776-1c23f39a/registry.npmjs.org/winston/-/winston-1.1.2.tgz
tar.unpack untar error /tmp/npm-776-1c23f39a/registry.npmjs.org/lodash/-/lodash-3.10.1.tgz
tar.unpack untar error /tmp/npm-776-1c23f39a/registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
Darwin 15.0.0
argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
node v4.2.2
npm v3.5.0
unexpected eof

If you need help, you may report this error at:
https://github.com/npm/npm/issues
Please include the following file with any support request:
/Documents/npm-debug.log

Bankims-MacBook-Pro:Documents bankimdebnath$

**Comment by bankim** [comment]
Hi Jbavari,

can you please help me in this..

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
