### ISSUE TITLE
Current working directory is not a Cordova based project

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#935]
_From @reynoldbhatia on April 14, 2016 20:16_

I have everything setup but when I try running 
ionic platform add android 

it just gives me an error saying Current working directory is not a Cordova based project

![image](https://cloud.githubusercontent.com/assets/11049768/14542293/41214666-025c-11e6-9125-3bfbe6a273fe.png)

_Copied from original issue: driftyco/ionic#6174_

**Comment by jgw96** [comment]
_From @dhirajb1989 on April 15, 2016 2:11_

Is config.xml present there???

**Comment by jgw96** [comment]
_From @reynoldbhatia on April 15, 2016 13:58_

Yes there is.

**Comment by jgw96** [comment]
@reynoldbhatia Hello! Sorry your having an issue getting started with your ionic app! Did you create this app with `ionic start` or did you git clone it from github? Also, do you have cordova installed?

**Comment by jgw96** [comment]
_From @reynoldbhatia on April 15, 2016 15:28_

I created it using ionic start. And yes, I have Cordova installed. Cordova create also works. The project created with Cordova create also gives the same error when I try adding the platform.

**Comment by jgw96** [comment]
@reynoldbhatia thanks for the info! So im gonna defer this issue over to the ionic-cli repo as the guys over there will be able to help you better with this issue than i can.

**Comment by tlancina** [comment]
Could you post the output of `ionic info` please?

**Comment by reynoldbhatia** [comment]
I am re-installing everything. I'll send it once it is done. Thanks.

**Comment by reynoldbhatia** [comment]
![capture](https://cloud.githubusercontent.com/assets/11049768/14644218/4cd3954c-061f-11e6-872c-c9124a252ab0.JPG)

The output to ionic info @tlancina

**Comment by reynoldbhatia** [comment]
Also, If I run `cordova platform add android` from inside the project folder, it works fine. But `ionic platform add android` gives the same error.

**Comment by tlancina** [comment]
Could you run it with the `--verbose` flag and post the out put please?
`ionic platform add android --verbose`, thanks!

**Comment by reynoldbhatia** [comment]
![capture](https://cloud.githubusercontent.com/assets/11049768/14644730/140ae182-0621-11e6-9651-c42e114ed305.JPG)

**Comment by reynoldbhatia** [comment]
I would like to add.... I have 2 other systems running on Windows 8.1 and Windows 10 which work fine. The system I am working on currently is Windows 7. Just in case, if the operating system needs something more to be done while setup.

**Comment by jgw96** [comment]
@reynoldbhatia what version of npm are you using? npm 2 or npm 3?

**Comment by reynoldbhatia** [comment]
2.15.1

**Comment by jgw96** [comment]
Ahh, could you try updating to npm 3? We've seen a couple of issues related to npm 2. To update npm you run `npm install -g npm`.

**Comment by jgw96** [comment]
Oh and then remove your node modules and then run `npm install` again.

**Comment by reynoldbhatia** [comment]
I did as you said. It did not work. Still giving me the same error.

**Comment by reynoldbhatia** [comment]
![capture](https://cloud.githubusercontent.com/assets/11049768/14652533/ba30448c-0642-11e6-87fd-6554970c662c.JPG)


Still getting the same error.

**Comment by sbesselsen** [comment]
For posterity: usually the solution is to make sure the is a www/ directory inside the root directory.

**Comment by hoodaajay99** [comment]
mkdir www in your project folder and it works well.

**Comment by dniccum** [comment]
@hoodaajay99 this solved my issue as well.

**Comment by warent** [comment]
@sbesselsen that was it

**Comment by westonganger** [comment]
+1 `mkdir www`

**Comment by fiznool** [comment]
This was the same issue for me.

I originally created an Ionic 2 app with `ionic start` on one machine, and committed and pushed to github. Then, I pulled down the code on a second machine, and tried to run `ionic platform add ios`. Since the `www` folder is `gitignore`d, it isn't committed to github, therefore the second machine's cloned codebase not contain a `www` folder, and the command fails.

As mentioned, one solution is to `mkdir www`. Another solution is to first run `ionic serve` on the second machine, which will automatically create the `www` folder. Afterwards, `ionic platform add` commands will work.

**Comment by VovanSuper** [comment]
yep, "./www" ... :)

**Comment by aaronksaunders** [comment]
if it is required to run, then why is it added to the `gitignore` file?

**Comment by dericeira** [comment]
@aaronksaunders That's the questions of 1 million dollars.

**Comment by fiznool** [comment]
@aaronksaunders probably for the same reason that _node_modules_ is part of `.gitignore`. These files are needed to run the app, but committing them would cause unnecessarily large and complex commits. Every time the files in www are built, the `main.js` file will be treated as a different file by source control. You wouldn't want that consuming your commit logs.

**Comment by aaronksaunders** [comment]
@fiznool - very thorough explanation however the one point i would disagree with is that the exclusion of the folder causes errors and the exclusion of `node_modules` does not so IMHO the comparison is not appropriate

**Comment by lufias** [comment]
should've added .gitkeep file or any other way to ensure the directory exist even if the content is never to be committed.

www/*
!www/.gitkeep

**Comment by Frutal1ty** [comment]
folder www is genereted every time you `ionic serve`

**Comment by lufias** [comment]
@Frutal1ty that is if you use ionic serve.. OP wants to deploy the app on device by adding in the android platform.. and calling run instead of serve.. that's when things doesn't work as it should.. no www folder were created..

**Comment by penglipurlara10** [comment]
I have the same problem, but i'm currently using phonegap because i'm new to mobile app development

**Comment by utsav-gupta** [comment]
I followed this whole discussion which helped me. I have my 2 cents which could help others. I would suggest it would be good idea for ionic to create  www if it is not there instead of error that "this is not a cordova directory". Somebody asked above why is www directry ignored if it is needed by ionic. The above fix would solve this problem too as we will not hav to upload www to git that way..

**Comment by alexunjm** [comment]
hi everybody!
check if www folder exist. If it doesn't exist, maybe you cloned your repo like me
I solved doing npm install, because the node_modules aren't in my repo, and finally, run "ionic serve" for check that my project is ok. With "ionic serve" command, www folder is created and now you can run "ionic add platform android" command

**Comment by Rombersoft** [comment]
I'm crying. I have same problem and directory www exists in my projects.

**Comment by khushbooInheritx** [comment]
make sure you are firing command from the root directory(write inside cmd: cd yourRootFolder) and www folder exists inside it.

**Comment by Rombersoft** [comment]
I know reason. It is that I've created project using Intel xdk not Cordova
command prompt.

03 апр. 2017 г. 8:52 пользователь "khushbooInheritx" <
notifications@github.com> написал:

**Comment by xbojer** [comment]
As stated before - problem is mostly missing www directory because of wrong .gitignore file...
This should be fixed. Manually creating www directory or starting ionic serve before for example ionic state restore is NOT a solution at all...

**Comment by santiq** [comment]
I had the same issue with my circle-ci build
What I did was add `mkdir www` before run `ionic cordova platform add android`

**Comment by dwieeb** [comment]
CLI 3.1.0 automatically creates the www directory. Please update.

**Comment by mikermcneil** [comment]
As a datapoint, I'm still seeing this error with a `www/` folder and the following system info:

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

∑ ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

Your system information:

Cordova CLI: 7.0.1 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.2.1 Build version 8C1002



******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
∑ 
∑ 
∑ ls -la .
total 48
drwxr-xr-x   15 mikermcneil  staff    510 Jun  7 08:37 .
drwxr-xr-x   21 mikermcneil  staff    714 Jun  7 08:33 ..
-rw-r--r--    1 mikermcneil  staff      0 Apr 27 14:49 .gitkeep
-rw-r--r--    1 mikermcneil  staff   5885 Apr 27 17:07 config.xml
drwxr-xr-x    3 mikermcneil  staff    102 Apr 27 17:07 hooks
-rw-r--r--    1 mikermcneil  staff     74 Apr 27 17:07 ionic.config.json
drwxr-xr-x  512 mikermcneil  staff  17408 May  9 20:15 node_modules
-rw-r--r--    1 mikermcneil  staff   1424 May  1 12:58 package.json
drwxr-xr-x    5 mikermcneil  staff    170 Apr 29 20:49 platforms
drwxr-xr-x   10 mikermcneil  staff    340 Apr 27 17:07 plugins
drwxr-xr-x    6 mikermcneil  staff    204 Apr 27 17:07 resources
drwxr-xr-x@  12 mikermcneil  staff    408 Jun  7 08:37 src
-rw-r--r--    1 mikermcneil  staff    465 Apr 27 17:07 tsconfig.json
-rw-r--r--    1 mikermcneil  staff    178 Apr 27 17:07 tslint.json
drwxr-xr-x    7 mikermcneil  staff    238 Apr 29 18:26 www
∑ 
```

**Comment by dwieeb** [comment]
`Ionic CLI Version: 2.2.3`

You are still on the old version. Please update.

**Comment by dgaurav-163** [comment]
Can you please first try "ionic build serve" then same error will occur
      L18:          this.platform.ready().then(() => {
      L19:              let browser = new InAppBrowser("https://www.techiediaries.com",'_blank');

Error: No platforms added to this project. Please use `cordova platform add <platform>`.
then call "cordova platform add <platform>".

It will work

**Comment by Reegan01** [comment]
simply add `ionic` in front of `cordova plugin add ...`  or  `cordova platform add android`  

So finally it look like `ionic cordova platform add...`

For this you must have latest ionic version

**Comment by Rand-om** [comment]
I had the same issue, but I used "ionic cordova platform add android", and it started to work perfectly!

![agenda](https://user-images.githubusercontent.com/11022987/33106414-b9e84126-cf10-11e7-8be7-6d668d6fb4b7.PNG)

**Comment by markbgh** [comment]
@Reegan01's worked for me with Ionic CLI v3.18.0 👍

**Comment by soumyarout** [comment]
If anyone is getting same error in adding adding plugins 
use the command like this 

`ionic cordova plugin add cordova-plugin-mfp`

**Comment by dwieeb** [comment]
The root of this issue is the following files must exist for the Cordova CLI to detect it as a Cordova project:

* `config.xml` - a file (not a symlink) that has read/write permissions for your user
* `www/` - a directory (not a symlink) that has read/write/execute permissions for your user

The Ionic CLI can detect and fix some problems with these files (all the `ionic cordova ...` commands run these checks), but sometimes it's not enough and you'll need to fix something manually. 

Locking this issue--it's ancient.
